[agent]
 hostname = "telegraf-02"


[[inputs.gnmi]]
 addresses = ["ceos-02:50051"]
 username = "${NETWORK_AGENT_USER}"
 password = "${NETWORK_AGENT_PASSWORD}"
 redial = "20s"
 # Exclude the "path" tag from the output
 tagexclude = ["path"]


 [[inputs.gnmi.subscription]]
   name = "interface"
   path = "/interfaces/interface/state/counters"
   subscription_mode = "sample"
   sample_interval = "10s"


 [[inputs.gnmi.subscription]]
   name = "interface"
   path = "/interfaces/interface/state/oper-status"
   subscription_mode = "sample"
   sample_interval = "10s"

[[processors.rename]]
  # Rename the tag "source" to "device"
  [[processors.rename.replace]]
    tag = "source"
    dest = "device"

# Telegraf Processor execd for dynamic data enrichment
[[processors.execd]]
  # Filter for "interface" metrics
  namepass = ["interface"]
  # Run the Nautobot data enrichment script
  command = ["python3", "/etc/telegraf/script.py"]
  # If script quits unexpectedly, wait 10 seconds before restarting
  restart_delay = "10s"

[[outputs.file]]
 files = ["stdout"]
